ui: mocha-bdd
browsers:
  - name: chrome
    version: 42..latest
  - name: safari
    version: 7..latest
  - name: firefox
    version: 36..latest
  - name: ie
    version: 10..latest
browserify:
  - transform: coffeeify
  - transform: brfs
  - options:
      extensions:
        - .coffee
